version: '3.8'

services:
  db:
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      # timezone inside container
      - TZ

      # necessary Postgres options/variables
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5433:5432

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_FILE: '${MB_DB_FILE}'
      MB_DB_TYPE: 'postgres'
      MB_DB_DBNAME: '${POSTGRES_DB}'
      MB_DB_PORT: 5432
      MB_DB_USER: '${POSTGRES_USER}'
      MB_DB_HOST: 'db'
      MB_DB_PASS: '${POSTGRES_PASSWORD}'
      JAVA_TIMEZONE: '${TZ}'
    ports:
      # <Port exposed>:<Port running inside container>
      - '${MB_PORT}:3000'
    volumes:
      # Volumes where Metabase data will be persisted
      - 'mb-data:/metabase-data'
      - './mb_plugins:/plugins'
    depends_on:
      - 'db'

volumes:
  db-data:
  mb-data:
